import Head from 'next/head'
import TransitionEffect from '@/components/TransitionEffect'

import HomePage from '../components/completed/HomePage'
import About from '../components/completed/About'
import Vignettes from '@/components/completed/Vignettes'
import Entreprises from '@/components/completed/Entreprises'
import VideoMontage from '@/components/completed/VideoMontage'

import HireMe from '@/components/HireMe'
import PhotoMotion from '@/components/PhotoFramerMotion'
import PhotoMotion2 from '@/components/completed/PhotoMotion'
import AnimatedMontagePhoto from '@/components/AnimatedMontagePhoto'
import ScrollToTop from '@/components/ScrollToTop'



export default function Home() {
  return (
    <>
      <Head>
        <title>Lucky Muller | Home</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      {/* <TransitionEffect /> */}
      
      <main>
        <HomePage />
        <About />
        {/* <HireMe /> */}
        <div className='w-full overflow-x-clip'>
        <VideoMontage />
        <PhotoMotion />
        <Vignettes />
        
        <Entreprises />
          
          {/* <AnimatedMontagePhoto />
          <PhotoMotion2 /> */}

          <HireMe />
          <ScrollToTop />
        </div>
      </main>
    </>
  )
}
